name: S3 to Power BI Workspace

on: 
  schedule:
  - cron: 0 6 * * *
  push:
    branches: [ "main" ]


jobs:    
  pull:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: S3 to Power BI Workspace
        id: nr-powerbi-workspace-deploy
        uses: bcgov/nr-powerbi-workspace-deploy@main
        env:
          PBI_FILE: 'Deployment Example.pbix'
          WORKSPACE_ENV: 'dev'
          DOMAIN: 'df'
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          OBJ_ID: ${{ secrets.OBJ_ID }}
          OBJ_KEY: ${{ secrets.OBJ_KEY }}
          OBJ_BUCKET: ${{ secrets.OBJ_BUCKET }}



